
package com.tr.cdb.vessel.location.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GlobalSatExport", targetNamespace = "http://webservice.vesseltracker.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GlobalSatExport {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.tr.cdb.vessel.location.ws.GlobalSatExportValue
     * @throws IncorrectPasswordException_Exception
     * @throws NoPermissionException_Exception
     * @throws UserNotFoundException_Exception
     * @throws AccountLockedException_Exception
     * @throws BadFormatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exportGlobalSatData", targetNamespace = "http://webservice.vesseltracker.com/", className = "com.tr.cdb.vessel.location.ws.ExportGlobalSatData")
    @ResponseWrapper(localName = "exportGlobalSatDataResponse", targetNamespace = "http://webservice.vesseltracker.com/", className = "com.tr.cdb.vessel.location.ws.ExportGlobalSatDataResponse")
    @Action(input = "http://webservice.vesseltracker.com/GlobalSatExport/exportGlobalSatDataRequest", output = "http://webservice.vesseltracker.com/GlobalSatExport/exportGlobalSatDataResponse", fault = {
        @FaultAction(className = BadFormatException_Exception.class, value = "http://webservice.vesseltracker.com/GlobalSatExport/exportGlobalSatData/Fault/BadFormatException"),
        @FaultAction(className = UserNotFoundException_Exception.class, value = "http://webservice.vesseltracker.com/GlobalSatExport/exportGlobalSatData/Fault/UserNotFoundException"),
        @FaultAction(className = IncorrectPasswordException_Exception.class, value = "http://webservice.vesseltracker.com/GlobalSatExport/exportGlobalSatData/Fault/IncorrectPasswordException"),
        @FaultAction(className = AccountLockedException_Exception.class, value = "http://webservice.vesseltracker.com/GlobalSatExport/exportGlobalSatData/Fault/AccountLockedException"),
        @FaultAction(className = NoPermissionException_Exception.class, value = "http://webservice.vesseltracker.com/GlobalSatExport/exportGlobalSatData/Fault/NoPermissionException")
    })
    public GlobalSatExportValue exportGlobalSatData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2)
        throws AccountLockedException_Exception, BadFormatException_Exception, IncorrectPasswordException_Exception, NoPermissionException_Exception, UserNotFoundException_Exception
    ;

}
