
package com.tr.cdb.vessel.location.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GlobalSatExportService", targetNamespace = "http://webservice.vesseltracker.com/", wsdlLocation = "http://webservice.vesseltracker.com/webservices/GlobalSatExport?WSDL")
public class GlobalSatExportService
    extends Service
{

    private final static URL GLOBALSATEXPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GLOBALSATEXPORTSERVICE_EXCEPTION;
    private final static QName GLOBALSATEXPORTSERVICE_QNAME = new QName("http://webservice.vesseltracker.com/", "GlobalSatExportService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservice.vesseltracker.com/webservices/GlobalSatExport?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GLOBALSATEXPORTSERVICE_WSDL_LOCATION = url;
        GLOBALSATEXPORTSERVICE_EXCEPTION = e;
    }

    public GlobalSatExportService() {
        super(__getWsdlLocation(), GLOBALSATEXPORTSERVICE_QNAME);
    }

    public GlobalSatExportService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GLOBALSATEXPORTSERVICE_QNAME, features);
    }

    public GlobalSatExportService(URL wsdlLocation) {
        super(wsdlLocation, GLOBALSATEXPORTSERVICE_QNAME);
    }

    public GlobalSatExportService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GLOBALSATEXPORTSERVICE_QNAME, features);
    }

    public GlobalSatExportService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GlobalSatExportService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GlobalSatExport
     */
    @WebEndpoint(name = "GlobalSatExportPort")
    public GlobalSatExport getGlobalSatExportPort() {
        return super.getPort(new QName("http://webservice.vesseltracker.com/", "GlobalSatExportPort"), GlobalSatExport.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GlobalSatExport
     */
    @WebEndpoint(name = "GlobalSatExportPort")
    public GlobalSatExport getGlobalSatExportPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.vesseltracker.com/", "GlobalSatExportPort"), GlobalSatExport.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GLOBALSATEXPORTSERVICE_EXCEPTION!= null) {
            throw GLOBALSATEXPORTSERVICE_EXCEPTION;
        }
        return GLOBALSATEXPORTSERVICE_WSDL_LOCATION;
    }

}
